# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_searchcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Jan', models.IntegerField()),
                ('Feb', models.IntegerField()),
                ('Mar', models.IntegerField()),
                ('Apr', models.IntegerField()),
                ('May', models.IntegerField()),
                ('Jun', models.IntegerField()),
                ('Jul', models.IntegerField()),
                ('Aug', models.IntegerField()),
                ('Sep', models.IntegerField()),
                ('Oct', models.IntegerField()),
                ('Nov', models.IntegerField()),
                ('Dec', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Searchcsv',
        ),
        migrations.DeleteModel(
            name='SearchISBN',
        ),
    ]
